//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charakter
    {
        public Charakter()
        {

        }
        public Charakter(String Name, Boolean isForceUser, String Side, System.Guid HomePlanet, Planet Planet)
        {
            this.Id = System.Guid.NewGuid();
            this.Name = Name;
            this.isForceUser = isForceUser == true ? 1 : 0;
            this.Side = Side;
            this.HomePlanet = HomePlanet;
            this.Planet = Planet;
        }

        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> isForceUser { get; set; }
        public string Side { get; set; }
        public System.Guid HomePlanet { get; set; }
    
        public virtual Planet Planet { get; set; }

        override
        public String ToString()
        {
            return "Mein Name ist " + Name + " ich komme von " + Planet.Name + ", wo " + Planet.Einwohnerzahl + " Charaktere leben und bin auf der " + Side + " Side.";
        }
    }
}
