//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planet()
        {
            this.Charakter = new HashSet<Charakter>();
        }

        public Planet(String PlanetName)
        {
            this.Charakter = new HashSet<Charakter>();
            this.Id = System.Guid.NewGuid();
            this.Name = PlanetName;
            this.Einwohnerzahl = 1;
        }

        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Einwohnerzahl { get; set; }
        public string Föderation { get; set; }
        public string Region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Charakter> Charakter { get; set; }
    }
}
